---
builds:
  - main: .
    binary: terraform-provider-ldap

    goos:
      - darwin
      - linux
      - windows

    goarch:
      - amd64

    env:
      - CGO_ENABLED=0

    ldflags: -extldflags="-static" -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
